//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomovaPrace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Clanek
    {

        [DisplayName("ID")]
        public int Id { get; set; }

        [DisplayName("Titulek")]
        [Required(ErrorMessage = "Titulek musí být vyplnìný.")]
        [AllowHtml]
        public string Titulek { get; set; }

        [DisplayName("Popisek")]
        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "Popisek musí být vyplnìný.")]
        [AllowHtml]
        public string Popisek { get; set; }

        [DisplayName("Datum vytvoøení")]
        public System.DateTime DatumVytvoreni { get; set; }

        [DisplayName("Obsah")]
        [AllowHtml]
        [Required(ErrorMessage = "Obsah musí být vyplnìný.")]
        public string Obsah { get; set; }

        [DisplayName("Kategorie")]
        [Required(ErrorMessage = "Kategorie musí být vyplnìný.")]
        public KategorieClanku Kategorie { get; set; }

        [DisplayName("Autor")]
        public int UzivatelId { get; set; }


        [DisplayName("Autor")]
        public virtual Uzivatel Autor { get; set; }
    }
}