//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomovaPrace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HodnoceniPrispevku
    {

        [DisplayName("ID")]
        public int Id { get; set; }

        [DisplayName("Hodnocení")]
        public int Hodnoceni { get; set; }

        [DisplayName("Pøíspìvek")]
        public int PrispevekId { get; set; }

        [DisplayName("Hodnotitel")]
        public int UzivatelId { get; set; }

        [DisplayName("Pøíspìvek")]
        public virtual Prispevek Prispevek { get; set; }

        [DisplayName("Hodnotitel")]
        public virtual Uzivatel Uzivatel { get; set; }
    }
}