//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomovaPrace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Interpret
    {

        [DisplayName("ID")]
        public int Id { get; set; }

        [DisplayName("Název")]
        [Required(ErrorMessage = "Název interpreta musí být vyplnìný.")]
        public string Nazev { get; set; }

        [DisplayName("Datum vytvoøení")]
        public System.DateTime DatumVytvoreni { get; set; }
    }
}
