//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomovaPrace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Komentar
    {

        [DisplayName("ID")]
        public int Id { get; set; }

        [DisplayName("Text")]
        [Required(ErrorMessage = "Text nesmí být prázdný.")]
        public string Text { get; set; }

        [DisplayName("Typ komentáøe")]
        public TypKomentare TypKomentare { get; set; }

        [DisplayName("Od")]
        public int UzivatelOdId { get; set; }

        [DisplayName("Komu")]
        public int UzivatelKomuId { get; set; }

        [DisplayName("Èlánek")]
        public int ClanekId { get; set; }

        [DisplayName("Datum pøidání")]
        public System.DateTime DatumPridani { get; set; }

        [DisplayName("Od")]
        public virtual Uzivatel UzivatelOd { get; set; }

        [DisplayName("Komu")]
        public virtual Uzivatel UzivatelKomu { get; set; }

        [DisplayName("Èlánek")]
        public virtual Clanek Clanek { get; set; }
    }
}