//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomovaPrace.Models
{
    using System;
    
    public enum TypRoleUzivatele : int
    {
        Administrator = 1,
        PrihlasenyUzivatel = 2,
        Redaktor = 3
    }
}
