//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomovaPrace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class Zadost
    {

        [DisplayName("ID")]
        public int Id { get; set; }

        [DisplayName("Komentáø")]
        [AllowHtml]
        public string Komentar { get; set; }

        [DisplayName("Typ žádosti")]
        public TypZadosti TypZadosti { get; set; }

        [DisplayName("Stav žádosti")]
        public StavZadosti StavZadosti { get; set; }

        [DisplayName("Odesílatel")]
        public int UzivatelOdId { get; set; }

        [DisplayName("Pøíjemce")]
        public int UzivatelKomuId { get; set; }

        [DisplayName("Interpret")]
        public int InterpretId { get; set; }

        [DisplayName("Pøíspìvek")]
        public int PrispevekId { get; set; }


        [DisplayName("Odesílatel")]
        public virtual Uzivatel ZadostOd { get; set; }

        [DisplayName("Pøíjemce")]
        public virtual Uzivatel ZadostKomu { get; set; }

        [DisplayName("Pøíspìvek")]
        public virtual Prispevek Prispevek { get; set; }

        [DisplayName("Interpret")]
        public virtual Interpret Interpret { get; set; }
    }
}