//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomovaPrace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Zprava
    {
        [DisplayName("ID")]
        public int Id { get; set; }

        [DisplayName("Čas odeslání")]
        public System.DateTime CasOdeslani { get; set; }

        [DisplayName("Text")]
        [Required(ErrorMessage = "Text nemùže být prázdný.")]
        public string Text { get; set; }

        [DisplayName("Odesílatel")]
        public int UzivatelOdId { get; set; }

        [DisplayName("Příjemce")]
        public int UzivatelKomuId { get; set; }


        [DisplayName("Odesílatel")]
        public virtual Uzivatel UzivatelOd { get; set; }

        [DisplayName("Příjemce")]
        public virtual Uzivatel UzivatelKomu { get; set; }

    }
}
